---
- name: Cancel quiet mode with API token
  uri:
    url: "{{ jenkins_url }}/cancelQuietDown"
    method: POST
    headers:
      Content-Type: "text/xml"
    status_code: 200,302
    url_username: "{{ jenkins_api_username }}"
    url_password: "{{ jenkins_api_token }}"
    force_basic_auth: true
    validate_certs: "{{ jenkins_https_validate_certs }}"
  when: jenkins_auth == "api"

- include_tasks: "get-crumb.yml"
  when: jenkins_auth == "crumb"

- name: Cancel quiet mode with crumb
  uri:
    url: "{{ jenkins_url }}/cancelQuietDown"
    method: POST
    headers:
      Content-Type: "text/xml"
      Cookie: "{{ jenkins_crumb_cookie }}"
      Jenkins-Crumb: "{{ jenkins_crumb_token }}"
    status_code: 200,302
    validate_certs: "{{ jenkins_https_validate_certs }}"
  when: jenkins_auth == "crumb"

- name: Cancel quiet mode with no security
  uri:
    url: "{{ jenkins_url }}/cancelQuietDown"
    method: POST
    headers:
      Content-Type: "text/xml"
    status_code: 200,302
    validate_certs: "{{ jenkins_https_validate_certs }}"
  when: jenkins_auth == "none"
