---
- include_tasks: "get-crumb.yml"
  when: jenkins_auth == "crumb"

- name: Set quiet mode with crumb
  uri:
    url: "{{ jenkins_url }}:{{ jenkins_port }}/quietDown"
    method: POST
    headers:
      Content-Type: "text/xml"
      Cookie: "{{ jenkins_crumb_cookie }}"
      Jenkins-Crumb: "{{ jenkins_crumb_token }}"
    status_code: 200,302
  when: jenkins_auth == "crumb"

- name: Set quiet mode with no security
  uri:
    url: "{{ jenkins_url }}:{{ jenkins_port }}/quietDown"
    method: POST
    headers:
      Content-Type: "text/xml"
    status_code: 200,302
  when: jenkins_auth == "none"
