# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN apt-get update && \
    apt-get install -y apt-transport-https aptitude bash ca-certificates sudo python \
        python-apt && \
    apt-get clean

RUN useradd -G sudo molecule
