# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 648ACFD622F3D138 && \
    apt-get update && \
    apt-get install -y apt-transport-https aptitude bash ca-certificates sudo python \
        python-apt && \
    apt-get clean

RUN useradd -G sudo molecule
