---

- name: Container is running
  docker_container:
    name: "{{ jenkins_docker_container_name }}"
    image: "{{ jenkins_docker_image }}:{{ jenkins_version }}"
    published_ports: "{{ jenkins_port }}:8080"
    volumes:
      - "{{ jenkins_home }}:/var/jenkins_home"
    env:
      JAVA_OPTS: "{{ jenkins_java_opts }}"
    restart: yes
